# Generated by Django 5.2.2 on 2025-06-08 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание заявки')),
                ('cost_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Себестоимость услуги')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='in_progress', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': [models.Case(models.When(status='in_progress', then=models.Value(0)), models.When(status='completed', then=models.Value(1)), models.When(status='canceled', then=models.Value(2)), default=models.Value(3), output_field=models.IntegerField()), '-updated_at'],
            },
        ),
    ]
