# Generated by Django 5.2.2 on 2025-06-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelTable(
            name='orderfile',
            table='order_files',
        ),
    ]
