# Generated by Django 5.2.2 on 2025-06-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderfile_options_alter_orderfile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('cost_price_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='orders.orders', verbose_name='Часть себестоимости')),
            ],
            options={
                'verbose_name': 'Часть кейса себестоимости',
                'verbose_name_plural': 'Части кейсов себестоимости',
                'db_table': 'order_cases',
            },
        ),
    ]
