# Generated by Django 5.2.2 on 2025-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercase',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
