# Generated by Django 5.2.2 on 2025-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordercase_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Себестоимость услуги'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общая стоимость'),
        ),
    ]
