# Generated by Django 5.2.2 on 2025-06-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True, verbose_name='telegram')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='телефон')),
                ('email_notification', models.BooleanField(default=True, verbose_name='Оповещения на почту')),
                ('telegram_notification', models.BooleanField(default=True, verbose_name='Оповещения в телеграм')),
                ('day_off_notification', models.BooleanField(default=False, verbose_name='Оповещения по выходным')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль менеджера',
                'verbose_name_plural': 'Профили менеджеров',
            },
        ),
    ]
