# Generated by Django 5.2.2 on 2025-06-07 19:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telegram_id', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True, verbose_name='telegram')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79999999999' or '89999999999'.", regex='^((\\+7)|8)\\d{10}$')], verbose_name='телефон')),
                ('email_notification', models.BooleanField(default=True, verbose_name='Оповещения на почту')),
                ('telegram_notification', models.BooleanField(default=True, verbose_name='Оповещения в телеграм')),
                ('day_off_notification', models.BooleanField(default=False, verbose_name='Оповещения по выходным')),
            ],
            options={
                'verbose_name': 'Профиль менеджера',
                'verbose_name_plural': 'Профили менеджеров',
                'db_table': 'user_profile',
            },
        ),
    ]
