# Generated by Django 5.2.2 on 2025-06-08 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Клиента')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=16, verbose_name='Второй телефон')),
                ('telegram', models.CharField(blank=True, max_length=55, verbose_name='telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
                'ordering': ['-id'],
            },
        ),
    ]
