# Generated by Django 5.2.2 on 2025-06-08 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79999999999' or '89999999999'.", regex='^((\\+7)|8)\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_2',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79999999999' or '89999999999'.", regex='^((\\+7)|8)\\d{10}$')], verbose_name='Второй телефон'),
        ),
    ]
